//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Mvc.Data
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Mvc.Data.Mapping;
    using Mvc.Models.Entities;
    
    public partial class LogisticsEntities : DbContext
    {
        static LogisticsEntities()
    	{ 
    		Database.SetInitializer<LogisticsEntities>(null);
    	}
    	
    	public LogisticsEntities() : base("name=LogisticsEntities")
        {
        }
    	
    	public LogisticsEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public LogisticsEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public LogisticsEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public LogisticsEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		//modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
    		modelBuilder.Configurations.Add(new Customer_Mapping());
    		modelBuilder.Configurations.Add(new Group_Mapping());
        }
    	
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Group> Groups { get; set; }
    }
}
